name: Testrun package

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'dev'
      - 'release/*'

permissions:
  contents: read

jobs:
  create_package:
    permissions: {}
    name: Package
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Checkout source
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Package Testrun
        shell: bash {0}
        run: cmd/package
      - name: Archive package
        uses: actions/upload-artifact@694cdabd8bdb0f10b2cea11669e1bf5453eed0a6 # v4.2.0
        with:
          name: testrun_package
          path: testrun*.deb

  install_package_20:
    permissions: {}
    needs: create_package
    name: Install on Ubuntu 20.04
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: Checkout source
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: testrun_package
      - name: Install dependencies
        shell: bash {0}
        run: sudo cmd/prepare
      - name: Install package
        shell: bash {0}
        run: sudo apt install ./testrun*.deb
      - name: Start testrun
        shell: bash {0}
        run: sudo testrun > >(tee testrun_output.log) 2>&1 &
      - name: Verify testrun started
        shell: bash {0}
        run: |
          sleep 5  
          if grep -q "API waiting for requests" testrun_output.log; then
            echo "Testrun started successfully."
          else
            echo "Testrun did not start correctly."
            cat testrun_output.log
            exit 1
          fi 

  install_package_22:
    permissions: {}
    needs: create_package
    name: Install on Ubuntu 22.04
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Checkout source
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: testrun_package
      - name: Install dependencies
        shell: bash {0}
        run: sudo cmd/prepare
      - name: Install package
        shell: bash {0}
        run: sudo apt install ./testrun*.deb
      - name: Start testrun
        shell: bash {0}
        run: sudo testrun > >(tee testrun_output.log) 2>&1 &
      - name: Verify testrun started
        shell: bash {0}
        run: |
          sleep 5  
          if grep -q "API waiting for requests" testrun_output.log; then
            echo "Testrun started successfully."
          else
            echo "Testrun did not start correctly."
            cat testrun_output.log
            exit 1
          fi 

  install_package_24:
    permissions: {}
    needs: create_package
    name: Install on Ubuntu 24.04
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - name: Checkout source
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: testrun_package
      - name: Install dependencies
        shell: bash {0}
        run: sudo cmd/prepare
      - name: Install package
        shell: bash {0}
        run: sudo apt install ./testrun*.deb
      - name: Start testrun
        shell: bash {0}
        run: sudo testrun > >(tee testrun_output.log) 2>&1 &
      - name: Verify testrun started
        shell: bash {0}
        run: |
          sleep 5  
          if grep -q "API waiting for requests" testrun_output.log; then
            echo "Testrun started successfully."
          else
            echo "Testrun did not start correctly."
            cat testrun_output.log
            exit 1
          fi 
